version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      
      - checkout

      - run:
          name: Setting up CI
          command: |
            wget https://releases.hashicorp.com/consul/1.4.3/consul_1.4.3_linux_amd64.zip
            unzip "consul_1.4.3_linux_amd64.zip"
            ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -dev -bind=$(hostname -I | awk '{print $1}' | xargs) -http-port 8501 -log-level=err &
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0

      - run:
          name: Running linter
          command: |
            sudo chown circleci:circleci /go/bin
            golangci-lint run -E golint --exclude-use-default=false

      - run:
          name: Run CI
          command: |
            make ci

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results